import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { getXataClient } from '../src/xata';
import Link from 'next/link';

export default function Home({ jobs }) {
  function reformatDate(fullDate) {
    const date = new Date(fullDate);
    return date.toDateString().slice(4);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {jobs.length > 0 ? (
          <div>
            {jobs.map(({ title, company, id, skills, date }) => (
              <div key={id}>
                <Link href={{ pathname: `job/${id}` }}>
                  <h1>{title}</h1>
                  <p>{company}</p>
                  {skills.map((skill, index) => (
                    <li key={index}>
                      <p>{skill}</p>
                    </li>
                  ))}

                  {reformatDate(date)}
                </Link>
              </div>
            ))}
          </div>
        ) : (
          <div>
            <p>No data in the database</p>
          </div>
        )}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const xata = await getXataClient();
  const jobs = await xata.db.Jobs.getAll();

  return {
    props: {
      jobs: jobs.map(({ replace, ...job }) => job),
    },
  };
}
